apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: translation-cloud-multi-tenant
  namespace: argocd
spec:
  description: Multi-Tenant Projekt für verschiedene Kunden
  sourceRepos:
    - https://github.com/apipinic/translation-service-infrastructure
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc  # Allows all future namespaces
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"