apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.awsLoadBalancerController.name }}
  namespace: {{ .Values.serviceAccounts.awsLoadBalancerController.namespace }}
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
