apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.translationService.name }}
  namespace: {{ .Values.serviceAccounts.translationService.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccounts.translationService.roleArn }}
  labels:
    app.kubernetes.io/name: translation-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
