apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.loginService.replicas }}
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
      - name: login-service
        image: {{ .Values.loginService.image }}
        ports:
        - containerPort: {{ .Values.loginService.port }}
      imagePullSecrets:
      - name: ghcr-secret
      nodeSelector:
        eks.amazonaws.com/nodegroup: login-nodegroup
