{{- range .Values.tenants }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  namespace: {{ .namespace }}
  labels:
    app: login-service
spec:
  replicas: {{ $.Values.loginService.replicas }}
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
      - name: login-service
        image: {{ $.Values.loginService.image.repository }}:{{ $.Values.loginService.image.tag }}
        imagePullPolicy: {{ $.Values.loginService.image.pullPolicy }}
        ports:
        - containerPort: {{ $.Values.loginService.port }}
      imagePullSecrets:
      - name: {{ $.Values.global.imagePullSecret }}
{{- end }}
