apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.translationService.replicas }}
  selector:
    matchLabels:
      app: translation-service
  template:
    metadata:
      labels:
        app: translation-service
    spec:
      serviceAccountName: translation-service-sa
      containers:
      - name: translation-service
        image: {{ .Values.translationService.image }}
        ports:
        - containerPort: {{ .Values.translationService.port }}
      imagePullSecrets:
      - name: ghcr-secret
      nodeSelector:
        eks.amazonaws.com/nodegroup: translation-nodegroup
