apiVersion: v1
kind: Service
metadata:
  name: translation-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: translation-service
  ports:
    - protocol: TCP
      port: {{ .Values.translationService.port }}
      targetPort: {{ .Values.translationService.port }}
