{{- range .Values.tenants }}
apiVersion: v1
kind: Service
metadata:
  name: translation-service
  namespace: {{ .namespace }}
  labels:
    app: translation-service
spec:
  selector:
    app: translation-service
  ports:
    - protocol: TCP
      port: {{ $.Values.translationService.port }}
      targetPort: {{ $.Values.translationService.port }}
  type: ClusterIP
{{- end }}
