apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: login-service
  ports:
    - protocol: TCP
      port: {{ .Values.loginService.port }}
      targetPort: {{ .Values.loginService.port }}
