namespace: translation-service-a
ingress:
  certificateArn: arn:aws:acm:eu-central-1:526290384516:certificate/ecd4b837-5593-4e09-84c8-056283ab2a17
  host: kundea.translation-cloud.at
loginService:
  replicas: 2 # Number of replicas for login service
  image: ghcr.io/apipinic/login-translation-service:868e63a # Login service image version
  port: 5000 # Port for the login service
translationService:
  replicas: 2 # Anzahl der Replikate für den translation service
  image: ghcr.io/apipinic/translation-service:868e63a # Container-Image für den translation service
  port: 5001 # Port für den translation service
serviceAccount:
  roleArn: arn:aws:iam::526290384516:role/ALBControllerIRSA # IAM role for service account
autoscaling:
  enabled: true # Enable auto-scaling
  minReplicas: 2 # Minimum number of replicas
  maxReplicas: 10 # Maximum number of replicas
  targetCPUUtilizationPercentage: 80 # Target CPU utilization for autoscaling
service:
  type: ClusterIP # Service type for internal communication (can be ClusterIP, NodePort, or LoadBalancer)
dockerconfigjson: "eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYXBpcGluaWMiLCJwYXNzd29yZCI6ImdocF82ZUdvNnRqcXltRHhVdFV2UFgydGF3bmhkVlBjZzkzNDQyTkMiLCJhdXRoIjoiWVhCcGNHbHVhV002WjJod1h6WmxSMjgyZEdweGVXMUVlRlYwVlhaUVdESjBZWGR1YUdSV1VHTm5PVE0wTkRKT1F3PT0ifX19Cg==" # Base64-encoded .dockerconfigjson data
