apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: translation-ingress
  namespace: kundea
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-set-headers: "custom-headers"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - translation-cloud.at
      secretName: translation-cloud-tls-secret
  rules:
    - host: translation-cloud.at
      http:
        paths:
          - path: /  # Verwende nur "/" ohne RegEx
            pathType: Prefix
            backend:
              service:
                name: translation-service
                port:
                  number: 80
          - path: /transcribe
            pathType: Prefix
            backend:
              service:
                name: translation-service
                port:
                  number: 80
          - path: /translate_live
            pathType: Prefix
            backend:
              service:
                name: translation-service
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: translation-service
                port:
                  number: 80
