apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: kundea
spec:
  selector:
    app: login-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
