apiVersion: v1
kind: Service
metadata:
  name: transcribe-service
  namespace: kundea
spec:
  selector:
    app: translation-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
  type: ClusterIP

