apiVersion: v1
kind: Service
metadata:
  name: translation-service
  namespace: kundea
spec:
  selector:
    app: translation-service
  ports:
  - protocol: TCP
    port: 443  # Use 443 for HTTPS
    targetPort: 5001
  type: LoadBalancer
