# Basis-Image mit Python
FROM python:3.9-slim

# Installiere Systemabhängigkeiten
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Install curl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Set build arguments
ARG JWT_SECRET_KEY
ARG SECRET_KEY

# Set environment variables
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV SECRET_KEY=$SECRET_KEY

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Kopiere requirements und installiere Python-Abhängigkeiten
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Kopiere den gesamten Code in den Container
COPY . .

# Exponiere den Port
EXPOSE 5000

# Starte die Applikation
CMD ["python", "app.py"]
