apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kundea
  namespace: argocd
spec:
  project: translation-cloud-multi-tenant
  source:
    repoURL: https://github.com/apipinic/translation-service-infrastructure
    targetRevision: HEAD
    path: k8s_multi/translation-service
    helm:
      valueFiles:
        - customers/kundea/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kundea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
