AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an OIDC Provider for EKS.

Parameters:
  OIDCProviderURL:
    Type: String
    Description: OIDC Provider URL for the EKS Cluster.

Resources:
  OIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: !Ref OIDCProviderURL
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - "e0e26d9ed4d742902002f2debc267811c0f31f1d"

Outputs:
  OIDCProviderArn:
    Description: The ARN of the OIDC provider.
    Value: !GetAtt OIDCProvider.Arn
    Export:
      Name: OIDCProviderArn
