name: Build and Push Docker Images

on:
  push:
    paths:
      - 'application/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to GHCR
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Debugging-Schritt nach Build
      - name: Debug Environment Variables
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}"
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}"
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}"


      # 3. Build and Push Login Translation Service
      - name: Build and Push Login Translation Service
        working-directory: ./application/login-service
        run: |
          docker build \
            --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
            --build-arg JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -t ghcr.io/${{ github.repository_owner }}/login-translation-service:latest .
          docker push ghcr.io/${{ github.repository_owner }}/login-translation-service:latest

      # 4. Build and Push Translation Service
      - name: Build and Push Translation Service
        working-directory: ./application/translation-service
        run: |
          docker build \
            --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
            --build-arg JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            --build-arg S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
            --build-arg DYNAMODB_TABLE=${{ secrets.DYNAMODB_TABLE }} \
            -t ghcr.io/${{ github.repository_owner }}/translation-service:latest .
          docker push ghcr.io/${{ github.repository_owner }}/translation-service:latest
