name: Deploy SAM Nested Stacks

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch
    paths:
      - 'infrastructure/**'  # Trigger only if changes are made in the infrastructure folder

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configure AWS CLI
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 3. Install AWS SAM CLI
    - name: Install AWS SAM CLI
      run: |
        sudo pip install --ignore-installed aws-sam-cli

    # 4. Package SAM Application
    - name: Package SAM Application
      run: |
        sam package \
          --template-file infrastructure/template.yaml \
          --output-template-file packaged.yaml \
          --s3-bucket ${{ secrets.S3_BUCKET }}

    # 5. Deploy SAM Application
    - name: Deploy SAM Application
      run: |
        sam deploy \
          --template-file packaged.yaml \
          --stack-name MyEKSStack \
          --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
          --parameter-overrides \
            EKSClusterName=MyEKSCluster AccountId=${{ secrets.AWS_ACCOUNT_ID }}
