name: Deploy CloudFormation

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configure AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 3. Validate CloudFormation Template (Optional but Recommended)
    - name: Validate CloudFormation template
      run: |
        aws cloudformation validate-template --template-body file://template.yaml

    # 4. Deploy CloudFormation Stack
    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file template.yaml \  # Adjust path if needed
          --stack-name MyEKSStack \  # Specify your stack name here
          --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
          --parameter-overrides EKSClusterName=MyEKSCluster AccountId=123456789012
